### PR TITLE
Adding appveyor script for windows builds

### PR DESCRIPTION
**Pull request by tjrileywisc**
Currently builds python 2.7.14 and 3.6.3 x64.
After building it runs nosetests (which is failing unfortunately).

Also added a small change to kissrandom.h for python 2.7 compatibility.

### CODE REVIEW

**Comment by erikbern** [comment]
This is great – how do we configure Github to run Appveyor tests? How do we display a badge etc :)

**Comment by tjrileywisc** [comment]
I think you'll have to create an appveyor account and add this repo. It's all set on mine- check here if you want to see what it looks like (I added custom messages for pending, success and failing to make it obvious that it's the windows version):

https://github.com/tjrileywisc/annoy

[(instructions here)](https://www.appveyor.com/docs/status-badges/#badges-for-projects-with-public-repositories-on-github-and-bitbucket)

Haven't yet figured out how to do separate python 2.7 and python 3.x badges. As far as I can tell you need to have separate branches.

**Comment by erikbern** [comment]
This is great – I actually have an Appveyor account set up with Annoy, just never got it working last time I tried (about 2 years ago)

**Comment by erikbern** [comment]
I'll merge this for now and will try to make it build on Appveyor

**Pull request merged**
