### PR TITLE
enable annoy seeding

### PR DESCRIPTION
**Pull request by yonromai**
@erikbern

### CODE REVIEW

**Comment by andy256** [comment]
You'll probably want to extend the RandRandom strict with this, and maybe implement it for the other (boost?) RANG that's available...

**Comment by andy256** [comment]
I hate autocorrect. Struct, RNG

**Comment by yonromai** [comment]
@andy256: perhaps a simple seeding would do?

**Comment by yonromai** [comment]
@andy256: Is this what you mean? It seems like the other RNGs (KissXYRandom) are already seeded

**Comment by a1k0n** [comment]
I was suggesting keeping the API to set the seed, and just pass it to the RNG... but I see now that it's part of the constructor, so that might be tricky. @erikbern thoughts?

**Comment by erikbern** [comment]
what's the point of this?

**Comment by andy256** [comment]
Reproducible builds?

**Comment by yonromai** [comment]
@andy256: is this more like what you had in mind?
(don't worry I'll squash if we want to merge...)

**Comment by erikbern** [comment]
i guess, but then what are reproducible builds useful for? :)

**Comment by yonromai** [comment]
lol, CI/testing are totally overrated ;)
@erikbern do you think this change would impact perf of annoy?

**Comment by erikbern** [comment]
i mean that if you have flakiness in your tests then you should fix that... don't rely on exact comparisons between the results arrays for instance, allow some percentage of missing values

see the unit tests for annoy – https://github.com/spotify/annoy/blob/master/test/annoy_test.py#L138

I don't have a problem with this PR just pointing out I think you're solving it in the wrong place

**Comment by yonromai** [comment]
actually AFAIC it's not for testing, but allowing to seed the RNG would be nice to make our pipelines idempotent. 
But I don't have superstrong feelings about this, so feel free to close the PR if you disagree.

**Comment by a1k0n** [comment]
Yeah, it would be a nice property if two speculatively executed tasks ended up with the same result.

**Comment by erikbern** [comment]
no i think seeding is generally good to have... for some things (like train/test split) it's crucial.

**Pull request merged**
