### PR TITLE
More precise Euclidean distance calculations.

### PR DESCRIPTION
**Pull request by LTLA**
Alternative solution to #314 for greater precision and AVX support.

### CODE REVIEW

**Comment by erikbern** [comment]
interesting. can you check if #315 is enough for what you need though? this PR roughly doubles the amount of arithmetic operations so unless it's truly needed i'd prefer to avoid it

**Comment by LTLA** [comment]
Hmm. I don't want to whale on this, but from my perspective, #315 doesn't seem to be sufficient. 

To demonstrate, here's a little elaboration of the program used in #314:

```cpp
#include <cstdio>
#include "annoylib.h"
#include "kissrandom.h"

typedef float ANNOYTYPE;

typedef AnnoyIndex<int, ANNOYTYPE, Euclidean, Kiss64Random> MyAnnoyIndex;

int main() {
    MyAnnoyIndex obj(1);

    ANNOYTYPE first=1.0001, second=1.0002, third=1.00015;
    obj.add_item(0, &first);
    obj.add_item(1, &second);
    obj.add_item(2, &third);

    obj.build(10);

    std::vector<int> stuff;
    std::vector<ANNOYTYPE> outdist;
    obj.get_nns_by_item(2, 2, -1, &stuff, &outdist);

    printf("%i %.10f\n", stuff[0], outdist[0]);
    printf("%i %.10f\n", stuff[1], outdist[1]);
    return 0;
}
```

On my computer, this gives me:

```
0 0.0000000000
1 0.0000000000
```

.... so not only is the distance wrong, item 3 is not even in its own nearest neighbor set! This seems particularly egregious when the differences between input items are well within `float` precision. I could also imagine a lot of breaking code that assumed the first element of `stuff` would be the item itself.

To be clear; the precision of the output distances themselves is not the problem, as I can just recompute them. The question is how much this loss of precision reduces the accuracy of the NN search, in a manner that is not easily adjustable by increasing `ntrees` or `search_k`. Certainly, I could switch to `double` in the example above (rather unhappily, because of the cost of time and memory), but Python and R users won't be able to do so at all, and I guess that's probably a substantial proportion of Annoy's user base.

Finally - unless I'm reading my code incorrectly - the proposed modification here should only add one subtraction operation plus an extra intermediate variable. Some testing suggests that it's about 50% slower. I'll admit that's not great, but if speed is a priority and accuracy is not, then a more natural way to make that sacrifice would be to reduce `search_k` directly (or indirectly, via a lower `ntrees`).

**Comment by LTLA** [comment]
Cool. I should mention that, in the context of the rest of the Annoy operations, the extra time required for these distance calculations seems negligible. I've tried with a 50000-by-20 random normal matrix, looking for the 20 nearest neighbors with 50 trees, and the performance hit from the switch is 1%.

**Comment by LTLA** [comment]
Nudging this PR. Just to clarify; the 50% slowdown refers to the head-to-head comparison between `dot()` and `euclidean_distance()`. This effect is considerably diluted when considering the Annoy algorithm in its entirety. In my applications, I see a 1-5% slowdown for the search, with more severe performance drops at higher `search_k` (as one might expect, given the context in which `distance()` is called). Nonetheless, this seems like a small price to pay for obtaining a correct final ranking among the collected `search_k` set when the differences between observations are somewhat small.

**Comment by erikbern** [comment]
will take a look shortly. busy life so i don't always have time to jump on pull requests quickly!

**Comment by erikbern** [comment]
Yeah I'm starting to lean towards just reverting my earlier optimization and going back to the (slightly slower) old method. Might as well revert for now so that things are working.

Have been very busy, hopefully if I have half an hour this weekend I'll take a look.

**Comment by erikbern** [comment]
merging this for now. i'm going to manually revert #272 as well

**Comment by erikbern** [comment]
@eddelbuettel take a look at https://github.com/spotify/annoy/pull/325

**Comment by eddelbuettel** [comment]
Perfect, thanks @erikbern. I had approximated this locally.

**Pull request merged**
