### PR TITLE
Add Go bindings via SWIG

### PR DESCRIPTION
**Pull request by rosmo**
This adds support for Go. I've created a different README for the Go stuff.

### CODE REVIEW

**Comment by erikbern** [comment]
wow this is excellent. ignore the appveyor tests

let's set up go tests separately in travis (i might be able to do that)

**Comment by rosmo** [comment]
Thanks. All kinds of suggestions, criticism and such are appreciated (first time using Go or SWIG, last time I touched C++ was years ago) :)

**Comment by erikbern** [comment]
it would be great if you can make the tests run in travis

let me see if i can set up the basics of it

**Comment by rosmo** [comment]
I can help if needed. The test is run by copying (I guess?) the annoy-test.go file under $GOPATH and running "go test".

**Comment by erikbern** [comment]
See #123!

**Pull request merged**
