### PR TITLE
incomplete change

### PR DESCRIPTION
**Pull request by LongbinChen**
hi, Eric, please feel free to take whatever you need.

### CODE REVIEW

**Comment by erikbern** [comment]
This looks great!

Did you consider using a plain old struct instead of protobuf? It's probably faster.

It might be worth just starting over with a new repository and calling it annoy2 or annul or something :)

**Comment by LongbinChen** [comment]
yes. i debated a lot.

protobuf would have very nice interface for whoever want to add new
indexing field into the system later; also it saves the work for
seriazation and deserialzation.

the downside is of course the overhead. however i think protobuf is highly
optimized so it is probably fine.

agree we can start another repo.

**Comment by LongbinChen** [comment]
maybe we can throw in a flask server to make it a full blown search engine
based on distance.

**Comment by erikbern** [comment]
Sure SGTM although I think in practice people might be fine just using the Python bindings and build a simple server around it

**Comment by erikbern** [comment]
If you want to move this to houzz/xyz, I'm happy to help. Was planning to do something under erikbern/ but I've been postponing it so long that it's better if someone else takes charge and I'm happy to contribute to it

**Comment by LongbinChen** [comment]
great. will do it soon.

**Comment by LongbinChen** [comment]
up now.

https://github.com/Houzz/annoy2

**Comment by piskvorky** [comment]
Just wondering... what does the move entail?

To be honest `erikbern/annoy` sounds a little safer to me, but I may not understand all the implications here.

**Comment by LongbinChen** [comment]
it is not quite about being safer or more danger. The codes are open so
there is not really much difference.  The houzz/annoy2 would be the place
for developing lmdb backend. if lmdb backend works, we can either merge it
back or to transfer to somewhere else.

**Comment by erikbern** [comment]
SGTM

The LMDB backend will have a different interface and indexes will not be binary compatible so I think it's the right way to go.

**Pull request closed without merging**
