### PR TITLE
use int for search_k rather than size_t

### PR DESCRIPTION
**Pull request by erikbern**
minor fix to deal with a sanitizer issue in https://github.com/eddelbuettel/rcppannoy/issues/56

### CODE REVIEW

**Comment by erikbern** [comment]
@eddelbuettel does this look right to you?

**Comment by eddelbuettel** [comment]
Just back in from a day of conferencing.  Looks pretty promising!

**Comment by eddelbuettel** [comment]
We also have another (minor) change (I missed) earlier in that we need an `inline` tag in front of two helper functions because folks may include the header multiple times.  See https://github.com/eddelbuettel/rcppannoy/pull/58 which does it but I think you were already in a thread or two where I suggested what @LTLA then quickly put into a PR.

**Comment by erikbern** [comment]
thanks, i'll inline those things in a separate pr

**Comment by eddelbuettel** [comment]
Looks good too.  Builds with both PRs, still get some g++-9 line noise. But hopefully the heavier SAN stuff is under control.

**Pull request merged**
