### PR TITLE
Feature/minor cleanup

### PR DESCRIPTION
**Pull request by eddelbuettel**
looks like you no longer need `_X1` and `_X2` in `Randomness()`

[ not sure why it shows me that I am 10 commits ahead of head -- I just merged with your master ]

### CODE REVIEW

**Comment by a1k0n** [comment]
try `git rebase origin/master`?

**Comment by eddelbuettel** [comment]
No, that is not it:

```
edd@max:~/git/annoy(master)$ git rebase origin/master 
Current branch master is up to date.
edd@max:~/git/annoy(master)$ 
```

**Comment by erikbern** [comment]
But something is weird. I can fix it in a separate commit

**Comment by erikbern** [comment]
Actually let me try to merge and if it causes something bad I'll revert

**Comment by erikbern** [comment]
looks like it worked

**Comment by eddelbuettel** [comment]
yes, all good now -- looks like we're in sync

and sorry by the way for the `RAND_MAX` egg I put up there....

**Comment by erikbern** [comment]
the `RAND_MAX` thing was weird. I don't understand why it didn't cause more issues :) I think the overflow ended up just mapping it to a different permutation of `0...RAND_MAX-1`

**Pull request merged**
