### PR TITLE
Adding Go to the build matrix

### PR DESCRIPTION
**Pull request by erikbern**

### CODE REVIEW

**Comment by erikbern** [comment]
@rosmo can you take a look at this? I can't get the build working in Travis – I don't think it's super hard

**Comment by erikbern** [comment]
There's some issue with swig: https://travis-ci.org/spotify/annoy/jobs/98008653

**Comment by rosmo** [comment]
I guess it might need swig 3.0. Unfortunately looks like swig 3.0 is only from Ubuntu trusty onwards (in trusty-backports).

**Comment by erikbern** [comment]
is it possible to add trusty-backports? i tried to figure out how to do it but wasn't able to

**Comment by rosmo** [comment]
I think trusty-backports is only for Ubuntu trusty. Can you upgrade to a newer release of Ubuntu on the CI test VM?

**Comment by erikbern** [comment]
Hm not sure if that's possible. Is it easy to install Swig 3 manually?

**Comment by rosmo** [comment]
Can you try adding this PPA https://launchpad.net/~teward/+archive/ubuntu/swig3.0?
```
deb http://ppa.launchpad.net/teward/swig3.0/ubuntu precise main 
deb-src http://ppa.launchpad.net/teward/swig3.0/ubuntu precise main 
```

**Comment by erikbern** [comment]
yeah seems to work – let me amend and try some more

**Comment by erikbern** [comment]
hm actually still same issue

```
$ swig3.0 -go -intgosize 64 -cgo -c++ src/annoygomodule.i
swig error : Unrecognized option -cgo
```

**Comment by erikbern** [comment]
If I remove the `-cgo` option I get tons of errors like this

```
# _/home/ubuntu/gopath/src/annoyindex
./annoygomodule_wrap.cxx: In function ‘void _wrap_AnnoyIndex_getNnsByItem__SWIG_0(void*)’:
./annoygomodule_wrap.cxx:411:19: error: ‘class std::vector<int>’ has no member named ‘len’
     swig_a->arg5->len = arg5->size();
```

**Comment by rosmo** [comment]
Let me set up an Ubuntu box this evening, and I'll try to compile it there.

**Comment by erikbern** [comment]
great – thanks.

**Comment by erikbern** [comment]
btw is it possible to use swig for the python module too? might simplify the code a bit

**Comment by rosmo** [comment]
I wouldn't use SWIG for anything unless I had to. I'm working on the Ubuntu compilation... it is quite more difficult than I thought.

**Comment by rosmo** [comment]
Allright, so you'll need to these two PPA repositories:
- https://launchpad.net/~evarlast/+archive/ubuntu/golang1.5
- https://launchpad.net/~rosmo/+archive/ubuntu/swig3.0.7

(eg. add-apt-repository ppa:evarlast/golang1.5 && add-apt-repository ppa:rosmo/swig3.0.7)

This should give you a newer Go than 1.0 (which is ancient) and also Swig 3.0.7 (-cgo was added in Swig 3.0.6). I managed to successfully build the example with these two.

**Comment by erikbern** [comment]
i'm not getting this to work on some other machine (could be some apt issue) but will try on travis!

**Comment by erikbern** [comment]
thanks a lot!

**Comment by rosmo** [comment]
Oh, and the swig command is: swig3.0 -go -intgosize 64 -cgo -c++ src/annoygomodule.i

**Comment by erikbern** [comment]
ok this seems to work now except the "cd" command fails because it's not a real shell command.

is there a way to run "go build" without the cd?

**Comment by erikbern** [comment]
trying something...

**Comment by rosmo** [comment]
That seems really strange. Maybe you can chain the shell commands into one command like ``/bin/sh -c "cd $GOPATH/src/annoyindex ; go build"``

**Comment by erikbern** [comment]
Not sure what to do about the latest issue: https://travis-ci.org/spotify/annoy/jobs/98461064

**Comment by rosmo** [comment]
It looks it's using some built-in version of Go (/home/travis/.gimme/versions/go1.4.2.linux.amd64/bin/go). Can you override it using /usr/bin/go (or whatever the path is)?

**Comment by erikbern** [comment]
lol $HOME in the commit msg got expanded to my local value of $HOME :)

**Comment by erikbern** [comment]
looks good except "go test" doesn't run anything

https://travis-ci.org/spotify/annoy/jobs/99135828

@rosmo any idea why?

**Comment by erikbern** [comment]
i'm fine merging this as-is, but let's follow up and make sure tests are run etc

**Comment by rosmo** [comment]
This should work:
```
mkdir -p $GOPATH/src/annoy_test
cp test/annoy_test.go  $GOPATH/src/annoy_test
cd  $GOPATH/src/annoy_test
go list -f '{{range .TestImports}}{{.}} > {{end}}' annoy_test | xargs go get
go test
```
It's probably a suboptimal way of doing things, but it seemed to work :)

**Comment by erikbern** [comment]
hm not sure if i can pipe data using tox but will try

**Comment by erikbern** [comment]
similarly "cd" won't work

**Comment by rosmo** [comment]
Maybe you can wrap that through /bin/sh? Like /bin/sh -c "go list..."

**Comment by erikbern** [comment]
yeah maybe. there must be some nicer way to do this though?

**Pull request merged**
