### PR TITLE
inremental add_item_to_index and load_memory

### PR DESCRIPTION
**Pull request by LongbinChen**
the main changes:

1. to avoid all the mass around mmap, i added a function, load_memory(), to load everything into the memory. The following operations would work on memory to avoid complications on mmap. Believe me I had tried to use stuffs like mremap and struggled a bit and feel we better off to load it memory and save to a different filename. 

2. the function add_item_to_index(T* w) would add a new item to existing index.  The newly added item will be saved at the space right after the last existing item. Before doing so, of course, I have to move the nodes at the position to the end of the array -- again, i have to remove the roots at the end of array when I load the file. 

3. also, in order to be able to move nodes around, i have to add an additional field "parent" to save a node's parents. 

4. i will wrap a python service ( probably based on tornado) to this index. so when there is a request to add an item, the service will load the index in memory, add the item, and save the updated index to a different file. the service keep a point to "current" index and "working" index. when serving traffic, the request still read from mmap.

### CODE REVIEW

**Comment by erikbern** [comment]
Let me take a look at this in the next few days

**Comment by erikbern** [comment]
On #1: I think *the* key feature of Annoy is that it uses mmap rather than allocates memory from the heap. This will not change. So please if you can figure out another way around it. One way is to keep the original chunk in mmap and use heap memory for any new nodes.

**Comment by erikbern** [comment]
On #2: You don't *have* to move the root nodes at the end of the index. It's nice if you do. But they only take up a very small amount of memory.

**Comment by erikbern** [comment]
On #3: This breaks backwards compatibility (that's probably why the unit test fails) so can you figure out a way around adding the "parent" field? I don't see it being used in many places so I'm not sure how it works

**Comment by erikbern** [comment]
This looks pretty cool overall. I really want to keep mmap and avoid adding the "parent" field.

There's also a lot of commits in this branch. Seems like only the first one is relevant for the PR. Can you remove the other commits for now? We can deal with them in a subsequent PR.

I hope we can merge this – would be a great addition.

I'm very curious about what you're using this for. Are you using it at Houzz?

**Comment by LongbinChen** [comment]
hi, Eric,
   thanks for the comments.
   I am building an image search engine whose core ranking function is knn.
I hope to build something like Solr that has the functionality of
 add/delete/update/filtering/sort, and probably with replication if i have
to shard the index.

   I like the mmap which can reduce the memory requirement when serving a
large index. The function "add_item_to_index" would require the serving
machine have big memories which might be a bummer. i will try to make it
work so that even when building index, we don't need a large memory.

  I didn't run the unit test because I don't know how to. can you let me
know how to run the unit test? thanks.


On Sat, Feb 28, 2015 at 9:24 AM, Erik Bernhardsson <notifications@github.com

**Comment by erikbern** [comment]
Ok, sounds great. Maybe I'll play around with your code. I might not understand all the complexity yet.

You should be able to run the unit tests using `nosetests`

**Comment by erikbern** [comment]
I want to pick this up. I might put together a separate PR and borrow a bit from this code. Incremental adds would be a great new feature.

**Comment by LongbinChen** [comment]
i have been looking into using LMDB as the backend storage for the index,
instead of using a simply memory-map array. There are some pros/cons for
using LMDB. Downside is that there would be some memory overheads. However
good side is that LMDB is a well-tested well-maintained memory-map
key-value store, with transaction support. I am afraid if we spend a lot of
time working on the Annoy's own memory map file operations, it is actually
just re-inventing the wheels of LMDB.

Thoughts?

On Sat, Aug 15, 2015 at 3:47 PM, Erik Bernhardsson <notifications@github.com

**Comment by LongbinChen** [comment]
one problem with Annoy we encountered in our system is that when we tried
to build a super large index, the system crashed because building indexing
uses the physical memory, not memory-map file.  Using LMDB could solve the
problem. Of course, we might work with memory array however it would be
much harder to work and the codes would be harder to maintain.

**Comment by erikbern** [comment]
I have been thinking about that case too. I think it's not too hard to fix
actually. Unfortunately mmap is not possible to resize, but you could
imagine splitting the memory in two slots where the first one is mmap and
second is dynamic. Then spill the second one to disk when needed. Or
something like that.

I never heard about LMDB but if it solves the issue then absolutely.

Either way my first step is probably to implement incremental add_item
after build() but before save(). This way I can avoid the memory management
issues for now.

**Comment by erikbern** [comment]
Read some more about LMDB. It seems interesting. I wonder what the overhead would be for int keys. But using non-integer keys has been a requested feature, so maybe it's fine incurring a small speed penalty

**Comment by wanderer2** [comment]
Hello Erik. Do you plan to integrate the proposed incremental update support?

**Comment by erikbern** [comment]
no plans

**Comment by mostafa8026** [comment]
It will be a great feature, if you plan to add incremental build. please take a look again.

**Pull request closed without merging**
