### PR TITLE
Windows Python 2.7 support

### PR DESCRIPTION
**Pull request by erikbern**
This should supersede #235

### CODE REVIEW

**Comment by erikbern** [comment]
merging this – @tjrileywisc can you see if this works?

**Comment by tjrileywisc** [comment]
@erikbern I'm afraid that didn't work. I'm seeing python crashes in 3.6 and 2.7 now, trying to figure out why.

I'm able to compile the precision_test.cpp example though in MSVC and it runs fine, so I think the problem is in the python module specifically.

**Comment by erikbern** [comment]
hm that's annoying. sorry i really thought my fix would resolve the issue

do you see any compiler warnings? anything else that could indicate what the issue is?

**Comment by erikbern** [comment]
Finding some evidence that MSVC adds memory checks to `memcpy`: http://www.informit.com/articles/article.aspx?p=2036582&seqNum=6

maybe add `#pragma runtime_checks("s", off)` at the top of the file?

**Comment by farizrahman4u** [comment]
@erikbern 

> hm that's annoying.

I see what you did there.

**Pull request merged**
