### PR TITLE
disable runtime memcpy check for visual studio

### PR DESCRIPTION
**Pull request by erikbern**
see discussion in #238

### CODE REVIEW

**Comment by erikbern** [comment]
@tjrileywisc let me know if this works!

**Comment by tjrileywisc** [comment]
Still didn't work I'm afraid. Looks like it's crashing python in the same place. It's crashing when running the nosetests. This is the last output just before the crash:

finding nbs for 161
finding nbs for 22055
finding nbs for 49154
finding nbs for 54985
finding nbs for 36080
finding nbs for 25961
finding nbs for 47264
limit: 10        precision:  13.56% avg time: 0.000068s
limit: 100       precision:  21.06% avg time: 0.000095s
limit: 1000      precision:  56.51% avg time: 0.000311s
limit: 10000     precision:  97.12% avg time: 0.002118s
.........

**Comment by tjrileywisc** [comment]
Okay, might have a signal here. Finally got to a point where I could use MSVC debug symbols to find out where exactly it's crashing:

`AnnoyIndex<int,float,Angular,Kiss64Random>::unload() Line 440`

... which I think sounds about right, from the output above. I think all of the tests run and then it crashes when finishing up.

It's crashing at this function:
`munmap(_nodes, size);`

`size` appears to be zero, because `_n_nodes` is zero.

**Comment by erikbern** [comment]
`munmap` is in `unload` which is run by the destructor. But it's only run if `_fd` is nonzero.

The only reason I can see that `_fd` would be nonzero would be if we try to load a file then fail. In that case it ends up being `-1`. Pushing a fix as a long shot – let's see if it helps

**Comment by erikbern** [comment]
It would be useful if you could run nosetests on each test file separately to see which one triggers the failure. Eg `python nosetests test/index_test.py` (I actually suspect that's the test that breaks)

**Comment by erikbern** [comment]
merging this for now... should be harmless at worst

**Comment by erikbern** [comment]
think this actually seems to work!

**Comment by tjrileywisc** [comment]
I think Python 3 is working again but 2.7 isn't according to the last time I ran nosetests, didn't yet get a chance to run individual tests for that version. Did they complete for you according to appveyor?

**Pull request merged**
