### PR TITLE
fix for duplicate roots

### PR DESCRIPTION
**Pull request by erikbern**
noticed a minor bug causing roots to be searched twice (useless)

currently seeing some weird segfaults on my computer triggered by something else, investigating in parallel

### CODE REVIEW

**Comment by a1k0n** [comment]
Whoa. Is one of the roots being added twice, or is the scan just seeing it twice somehow?

**Comment by erikbern** [comment]
the latter

**Comment by erikbern** [comment]
it would blow up the search time by a factor of (trees + 1) / trees so not that much

**Comment by a1k0n** [comment]
Hm. I don't understand how... but that code isn't the clearest...

**Comment by erikbern** [comment]
i copy the roots to the end of the index. but if the last item of the index was already a root then you end up having n+1 roots at the end of the index. the way annoy finds the roots is it just takes the last few nodes that has the biggest number of descendants. so that would include the last root twice (and all the other roots once)

**Pull request merged**
